### ISSUE TITLE
Rename repo

### ISSUE THREAD

**Issue by MissPhilbin** [raspberrypilearning/style-guide#14]
Hi lovely comms team,

I was wondering if we could rename the repo to better reflect its contents when we are searching on github to something like: copy-style-guide? 

Also I'm not sure if you are aware but we've always used the wiki on [resources-dev](https://github.com/raspberrypilearning/resources-dev) for the style guides. The copy style guide should really be part of the wiki rather than a separate repo but I'm not sure it really matters other than for keeping the orgs repos tidy. 

I'd really welcome your thoughts, thanks!

**Comment by JaninaPi** [comment]
The resources-dev repo links to this style guide now, and I believe the guide is linked to in other docs as well now, so I think it's best to leave it where it is.

I kind of agree with the name, not sure how to go about renaming a repo though...
