### ISSUE TITLE
Style guide for resources is inconsistent for names on boards (HATs)

### ISSUE THREAD

**Issue by DaddyTheRunner** [raspberrypilearning/style-guide#15]
The examples in the following row in the style guide table for resources need to be updated to be consistent with the guidance in the first column:

| Item | Format | Notes |
|-------------------------------------------|------|--------------------------------------------|
| Words printed on a board (e.g. a HAT) | Bold | Example: Servos, Input, Output, Motion. |

I believe the row should look like this:

| Item | Format | Notes |
|-------------------------------------------|------|--------------------------------------------|
| Words printed on a board (e.g. a HAT) | Bold | Example: **Servos**, **Input**, **Output**, **Motion**. |

**Comment by jennirpf** [comment]
checked and updated

**Comment by jennirpf** [comment]
checked and updated
