### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by bennuttall** [raspberrypilearning/style-guide#17]
Suggestions for missing terms or request for clarification:

- Minecraft / Minecraft Pi / Minecraft: Pi edition / mcpi
- *GPIO Zero* is the name of the project, but *gpiozero* is an acceptable alternative when referring to the *module*
- guizero
- cli (command line interface)
- API
- Mu (editor)
- Paradigm
- APT is not really an acronym. It was originally, it's just 'apt' now.
- PIXEL / RPD / ?
- RetroPiE (the E stands for 'emulator')
- SPI
- I2C or I<sup>2</sup>C?
- Pimoroni / Adafruit / etc?
- Jam / Raspberry Jam
- PiNet
- Netboot, etc?
- Mythic Beasts (+ clarity of possessive)
- Node (as in Node JS not NODE-RED)
- PyGame Zero
- tarball
- cron / contab
- Raspbian (Wheezy / Jessie / Stretch)
- Debian (Wheezy / Jessie / Stretch)
- RTFM :)

antenna missing closing bracket

Also could definitely do with more clarity on the usage of "pope" :)

:+1:

**Comment by JaninaPi** [comment]
Thanks Ben, I included the ones that I think are useful :)
