### ISSUE TITLE
Advice on time format seems surprising

### ISSUE THREAD

**Issue by helenlynn** [raspberrypilearning/style-guide#7]
https://github.com/raspberrypilearning/style-guide#time-and-date

"1615h" strikes me as a little surprising in British English, as well as rather military in style! Would anyone else support standardising on an alternative format?

**Comment by LizUpton** [comment]
Go for it; I'm pretty ambivalent. What's in the Oxford Guide to Style? (I think there is a copy on or around my desk - good luck with that.) Otherwise, happy to go with your preference.

**Comment by LornaLynch** [comment]
I have a copy at home if you can't find Liz's one, Helen. Can check later if you need.

**Comment by jennirpf** [comment]
It looks like the style guide has been updated since this ticket was opened, so I will close this.
