### ISSUE TITLE
Format for series titles

### ISSUE THREAD

**Issue by LornaLynch** [raspberrypilearning/style-guide#9]
With regard to formatting of series titles (esp the Essentials books): I have checked the Oxford Guide, which states that series titles should be set in Roman type without quotation marks. **Fictional** series should be set in italics or set within quotation marks. I think it would be helpful to state our preferred format in the style guide, if we are going to diverge from the OSG.

**Comment by lauraclay** [comment]
Er, don't we already do that in the 'Titles of other works' section?

**Comment by LornaLynch** [comment]
A note for series titles would be helpful, though, unless "*The MagPi* Essentials" is actually part of the  book title. The book title is, for example, *Learn to Code with C*, which is volume 8 of Raspberry Pi's *The MagPi* Essentials series.
